### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by unknowna17** [PySimpleGUI/PySimpleGUI-Photo-Colorizer#3]
Hi, i am using Python IDEL and Visual Studio on windows to load up this program however i keep getting the same error message that  colorization_release_v2.caffemodel has not been loaded into my model folder, where is the model folder, i am new to python and i am doing a project on colourisation. I need assistant of how to make this work, btw i have the latest versions of all the software and have installed everything, its just saying im missing the file.

**Comment by PySimpleGUI** [comment]
Did you download this file?

https://www.dropbox.com/s/dx0qvhhp5hbcx7z/colorization_release_v2.caffemodel?dl=1

**Comment by unknowna17** [comment]
Yes I did, how do I open it??

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/142513183-ad5312b4-0afa-4baf-a2c0-986237ddf29c.png)

It needs to be placed in the models folder.  If you look at the repo, you'll see the code and then in the same folder is a "model" folder.   Make sure you place this file in that folder.  

A troubleshooting tip....

Take a look at the code for the error message and you'll see why you're getting it.

**Comment by unknowna17** [comment]
<img width="951" alt="Capture" src="https://user-images.githubusercontent.com/94654086/142513748-0bff6397-1998-459b-8022-8b3ec8521e24.PNG">

Where is the model folder, i cant find the repo on this, can you guide me please

**Comment by unknowna17** [comment]
i cant seem to find the repo, where abouts is it

**Comment by unknowna17** [comment]
i have got all the files, i dont see what is wrong here
![Uploading Capture.PNG…]()

**Comment by unknowna17** [comment]
![Uploading Capture.PNG…]()

**Comment by unknowna17** [comment]
<img width="949" alt="Capture" src="https://user-images.githubusercontent.com/94654086/142516166-1391c8b9-8378-42f4-bde6-8bb753ca1aa2.PNG">

**Comment by unknowna17** [comment]
pts_in_hull wont open properly aswell

**Comment by PySimpleGUI** [comment]
Follow these steps:
1. Download this repo (this repositorty) as a zip file

![SNAG-1469](https://user-images.githubusercontent.com/46163555/142624449-51464026-696e-4dc4-953f-2c07cae93d0d.jpg)

2. Unzip into a folder


![SNAG-1470](https://user-images.githubusercontent.com/46163555/142624471-eba81f6f-1428-4f8d-9aec-ff31cf16b8e6.jpg)

3. Download the file `colorization_release_v2.caffemodel`
4. Place this file in the model folder that ZIP created when you unzipped the repo files
5. Run the program `PySimpleGUI_Colorizer.py`

![image](https://user-images.githubusercontent.com/46163555/142624265-27706a0c-489c-4e15-a3eb-2488329f32e1.png)

**Comment by PySimpleGUI** [comment]
It's been over 6 months, so closing this one....
